### ISSUE TITLE
get_ci_vm.sh problems with deleting on VM if image ID gets updated on main

### ISSUE THREAD

**Issue by Luap99** [containers/automation_images#330]
Not sure if this is the right place to file this, feel free to move it elsewhere if not.

Basically I run into a small corner case with get_cn_vm.sh today.
Last week I used it to create a VM to reproduce a flake. I left this VM running for a long time because of this. Now in the meantime the cirrus image id (IMAGE_SUFFIX) was updated on main.
Now when I run get_ci_vm.sh again instead of the normal the VM exists already and I can attached to it again I got a new VM even though the old one was still running likely because the VM name contains the ID (which makes sense) so it did not find the one with the old name.

I wanted to delete the old VM with the script but this was no longer an option because it created a new VM. I was able to work around this by checking out an older commit with the correct image ID.

I found this rather surprising, I am not sure if this can/should be fixed but at least it should be made more obvious to the user of the script that there is still an older VM IMO.

cc @cevich

**Comment by cevich** [comment]
> Not sure if this is the right place to file this

It is.

> I left this VM running for a long time because of this.

This isn't the intended use-case for this tool, but I won't you're usage because of of convenience.

> I found this rather surprising, I am not sure if this can/should be fixed but at least it should be made more obvious to the user of the script that there is still an older VM IMO.

I completely understand.  Different clouds handle VM 'names' slightly differently, for example this results in a bunch more code being needed for AWS VMs.  I'm not sure there is a good way to address this :confused: 

Off hand, the only way I can imagine fixing this would be to use a suffix composed from a hash of (perhaps) the repo-name + task-name string.  It would probably need to be some kind of simple CRC16 hash though, because both cloud providers have character limits for their names.

Could something like that be a workable solution do you think?

**Comment by Luap99** [comment]
I mean wontfix is a perfectly acceptable answer to me.

Would it be easy to simply just list all active VM's for my account when we launch the script? But this is really not that important to me, I guess we always get the email reminder in case I forgot one.

**Comment by cevich** [comment]
> I mean wontfix is a perfectly acceptable answer to me.

Noted, thanks for the clarification.

> Would it be easy to simply just list all active VM's for my account

Possible yes, easy maybe not.  AWS and GCE and the tooling handle VM names completely differently.  Both are capable of "grooming" search output into a human-friendly format, but they use a fairly complex general-purpose specification "language".  Even if it could list the names, it would still be left up to the user to pick the "right" .cirrus.yml to run against.

Honestly, picking a different VM naming scheme is probably an easier fix, but using a hash will make the names unreadable as to their source image (i.e. in the notification mail).

I think I am going to close this, since I don't think it's the right tool.  If in the future you need a more complex setup to hack on, feel free to ping me.  We can always rename the VMs manually and/or label them for identification or so the monitoring job skips over them.
